[tool.poetry]
name = "@voltz-protocol/transformer-v2"
version = "1.0.0"
description = "Voltz V2 Google Dataflow Transformer"
authors = ["Voltz Protocol"]

[tool.poetry.dependencies]
python = "^3.11"
apache-beam = { version = "^2.46.0", extras = ["gcp"] }
pytest = "^7.1.3"

[tool.poetry.dev-dependencies]
flake8 = "^6.0.0"
black = "^23.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"