[GLOBAL]
pants_version = "2.15.1"

backend_packages = [
  "pants.backend.build_files.fmt.black",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy"
]

[source]
root_patterns = [
    # The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
    "/pypackages/risk_engine"
]
marker_filenames = ["setup.py"]

[python]
# Enable the "resolves" mechanism, which turns on lockfiles for user code. See
# https://www.pantsbuild.org/docs/python-third-party-dependencies. This also adds the
# `generate-lockfiles` goal for Pants to generate the lockfile for you.
interpreter_constraints = ["==3.11.*"]
enable_resolves = true

[python-bootstrap]
search_path = [
    "/usr/local/bin",
]

[python.resolves]
python-default = "defaultpy.lock"

[mypy]
config = "mypy.ini"

[flake8]
config = ".flake8"
args = ["--output-file=reports/report.txt"]

[isort]
config = [".isort.cfg"]

[pytest]
version = "pytest==7.0.1"
