COLLATERAL_TOKEN = 'USDC'
INITIAL_FIXED_RATE = 0.05
RISK_PARAMETER = 0.02
IM_MULTIPLIER = 1.5
SLIPPAGE_PHI = 0.01 # todo: double check definition
SLIPPAGE_BETA = 0.02 # todo: double check definition
LP_SPREAD = 0.005
IS_TRADER_VT = True
MAKER_FEE = 0
TAKER_FEE = 0.0001
GWAP_LOOKBACK = 3600 # todo: double check if in seconds and change var name accordingly
LIQUIDATOR_REWARD = 0.01