COLLATERAL_TOKEN_NAME = 'USDC'
INITIAL_FIXED_RATE = 0.05
RISK_PARAMETER = 0.02
IM_MULTIPLIER = 1.5
SLIPPAGE_PHI = 0.01
SLIPPAGE_BETA = 0.02
LP_SPREAD = 0.005
MAKER_FEE = 0.0
TAKER_FEE = 0.0
# todo: double check if in seconds and change var name accordingly
GWAP_LOOKBACK = 3600
LIQUIDATOR_REWARD = 0.01
