from abc import ABCMeta, abstractmethod


class TradingStrategy(object):
    """
    Strategy is an abstract base class providing an interface for
    all subsequent (inherited) strategy handling objects.
    The goal of a (derived) Strategy object is to generate Signal
    objects for particular tokens based on the inputs of rates
    generated by a DataHandler object.
    This is designed to work both with historic and live data as
    the Strategy object is agnostic to the data source,
    since it obtains the rate tuples from a queue object.
    All logic for performing specific tradng instructions to generate
    different trading event simulations inherits from this abstract base class
    """

    __metaclass__ = ABCMeta

    @abstractmethod
    def calculate_signals(self, event):
        """
        Provides the mechanisms to calculate the list of signals.
        """
        raise NotImplementedError("Should implement calculate_signals()")