import { GetMarginAccountsResponse } from './types';

export const mockedMarginAccounts: GetMarginAccountsResponse['marginAccounts'] =
  [
    {
      id: '1',
      chainId: 1,
      name: 'A Wild Broccoli 🥦',
      balance: 123456,
      positionsCount: 1,
      marginRatioPercentage: 15,
      marginRatioHealth: 'healthy',
    },
    {
      id: '2',
      chainId: 43114,
      name: 'Moonwalking Astronaut 🚀',
      balance: 98765,
      positionsCount: 2,
      marginRatioPercentage: 30,
      marginRatioHealth: 'healthy',
    },
    {
      id: '3',
      chainId: 42161,
      name: 'Disco Panda 🐼🕺',
      balance: 65432,
      positionsCount: 3,
      marginRatioPercentage: 45,
      marginRatioHealth: 'warning',
    },
    {
      id: '4',
      chainId: 43114,
      name: 'Pizza Lover 🍕❤️',
      balance: 54321,
      positionsCount: 4,
      marginRatioPercentage: 60,
      marginRatioHealth: 'warning',
    },
    {
      id: '5',
      chainId: 43114,
      name: 'Crypto Surfer 🏄‍♂️',
      balance: 87654,
      positionsCount: 5,
      marginRatioPercentage: 75,
      marginRatioHealth: 'warning',
    },
    {
      id: '6',
      chainId: 1,
      name: 'Captain Doughnut 🍩⚓️',
      balance: 23456,
      positionsCount: 6,
      marginRatioPercentage: 90,
      marginRatioHealth: 'danger',
    },
    {
      id: '7',
      chainId: 42161,
      name: 'Zombie Unicorn 🦄🧟',
      balance: 34567,
      positionsCount: 7,
      marginRatioPercentage: 20,
      marginRatioHealth: 'healthy',
    },
    {
      id: '8',
      chainId: 42161,
      name: 'Fluffy Cactus 🌵🌈',
      balance: 45678,
      positionsCount: 8,
      marginRatioPercentage: 35,
      marginRatioHealth: 'healthy',
    },
    {
      id: '9',
      chainId: 5,
      name: 'Robot DJ 🤖🎧',
      balance: 56789,
      positionsCount: 9,
      marginRatioPercentage: 50,
      marginRatioHealth: 'warning',
    },
    {
      id: '10',
      chainId: 1,
      name: 'Pancake Master 🥞👑',
      balance: 78901,
      positionsCount: 10,
      marginRatioPercentage: 65,
      marginRatioHealth: 'warning',
    },
    {
      id: '11',
      chainId: 5,
      name: 'Ninja Turtle 🐢🥷',
      balance: 34567,
      positionsCount: 11,
      marginRatioPercentage: 80,
      marginRatioHealth: 'warning',
    },
    {
      id: '12',
      chainId: 1,
      name: 'Mermaid Diva 🧜‍♀️🎤',
      balance: 23456,
      positionsCount: 12,
      marginRatioPercentage: 10,
      marginRatioHealth: 'healthy',
    },
    {
      id: '13',
      chainId: 1,
      name: 'Sushi Addict 🍣🍱',
      balance: 87654,
      positionsCount: 13,
      marginRatioPercentage: 25,
      marginRatioHealth: 'healthy',
    },
    {
      id: '14',
      chainId: 1,
      name: 'Pixel Wizard 🧙‍♂️🎮',
      balance: 76543,
      positionsCount: 14,
      marginRatioPercentage: 40,
      marginRatioHealth: 'healthy',
    },
    {
      id: '15',
      chainId: 1,
      name: 'Space Penguin 🐧🪐',
      balance: 65432,
      positionsCount: 15,
      marginRatioPercentage: 55,
      marginRatioHealth: 'warning',
    },
    {
      id: '16',
      chainId: 42161,
      name: 'Gardening Guru 🌼🌿',
      balance: 54321,
      positionsCount: 16,
      marginRatioPercentage: 70,
      marginRatioHealth: 'warning',
    },
    {
      id: '17',
      chainId: 1,
      name: 'Coffee Connoisseur ☕️🌟',
      balance: 98765,
      positionsCount: 17,
      marginRatioPercentage: 85,
      marginRatioHealth: 'warning',
    },
    {
      id: '18',
      chainId: 43114,
      name: 'Galactic Explorer 🚀🪐',
      balance: 87654,
      positionsCount: 18,
      marginRatioPercentage: 25,
      marginRatioHealth: 'healthy',
    },
    {
      id: '19',
      chainId: 42161,
      name: 'Yoga Master 🧘‍♀️🌞',
      balance: 34567,
      positionsCount: 19,
      marginRatioPercentage: 40,
      marginRatioHealth: 'healthy',
    },
    {
      id: '20',
      chainId: 43114,
      name: 'Crypto Artist 🎨💎',
      balance: 65432,
      positionsCount: 20,
      marginRatioPercentage: 55,
      marginRatioHealth: 'warning',
    },
    {
      id: '21',
      chainId: 42161,
      name: 'Mountain Trekker ⛰️🥾',
      balance: 56789,
      positionsCount: 21,
      marginRatioPercentage: 70,
      marginRatioHealth: 'warning',
    },
    {
      id: '22',
      chainId: 43114,
      name: 'Code Wizard 👩‍💻🔮',
      balance: 45678,
      positionsCount: 22,
      marginRatioPercentage: 85,
      marginRatioHealth: 'warning',
    },
    {
      id: '23',
      chainId: 5,
      name: 'Artificial Intelligence 🤖🧠',
      balance: 78901,
      positionsCount: 23,
      marginRatioPercentage: 25,
      marginRatioHealth: 'healthy',
    },
    {
      id: '24',
      chainId: 1,
      name: 'Bookworm 📚🐛',
      balance: 65432,
      positionsCount: 24,
      marginRatioPercentage: 40,
      marginRatioHealth: 'healthy',
    },
    {
      id: '25',
      chainId: 5,
      name: 'Gourmet Chef 🍽️👨‍🍳',
      balance: 54321,
      positionsCount: 25,
      marginRatioPercentage: 55,
      marginRatioHealth: 'warning',
    },
    {
      id: '26',
      chainId: 1,
      name: 'Beach Bum 🏖️🌴',
      balance: 87654,
      positionsCount: 26,
      marginRatioPercentage: 70,
      marginRatioHealth: 'warning',
    },
    {
      id: '27',
      chainId: 43114,
      name: 'Space Cowboy 🤠🚀',
      balance: 23456,
      positionsCount: 27,
      marginRatioPercentage: 85,
      marginRatioHealth: 'warning',
    },
    {
      id: '28',
      chainId: 42161,
      name: 'Music Producer 🎶🎧',
      balance: 34567,
      positionsCount: 28,
      marginRatioPercentage: 25,
      marginRatioHealth: 'healthy',
    },
    {
      id: '29',
      chainId: 1,
      name: 'Volleyball Enthusiast 🏐🌞',
      balance: 56789,
      positionsCount: 29,
      marginRatioPercentage: 40,
      marginRatioHealth: 'healthy',
    },
    {
      id: '30',
      chainId: 43114,
      name: 'Astronomy Lover 🔭🌌',
      balance: 45678,
      positionsCount: 30,
      marginRatioPercentage: 55,
      marginRatioHealth: 'warning',
    },
    {
      id: '31',
      chainId: 42161,
      name: 'Hiking Pro 🥾🌲',
      balance: 78901,
      positionsCount: 31,
      marginRatioPercentage: 70,
      marginRatioHealth: 'warning',
    },
    {
      id: '32',
      chainId: 5,
      name: 'Cryptocurrency Enthusiast 💰🚀',
      balance: 23456,
      positionsCount: 32,
      marginRatioPercentage: 85,
      marginRatioHealth: 'warning',
    },
    {
      id: '33',
      chainId: 1,
      name: 'Movie Buff 🎬🍿',
      balance: 54321,
      positionsCount: 33,
      marginRatioPercentage: 25,
      marginRatioHealth: 'healthy',
    },
    {
      id: '34',
      chainId: 5,
      name: 'Eco Warrior 🌱🌍',
      balance: 65432,
      positionsCount: 34,
      marginRatioPercentage: 40,
      marginRatioHealth: 'healthy',
    },
    {
      id: '35',
      chainId: 43114,
      name: 'Robo Samurai 🤖⚔️',
      balance: 56789,
      positionsCount: 35,
      marginRatioPercentage: 55,
      marginRatioHealth: 'warning',
    },
    {
      id: '36',
      chainId: 42161,
      name: 'Tropical Paradise 🏝️🌺',
      balance: 45678,
      positionsCount: 36,
      marginRatioPercentage: 70,
      marginRatioHealth: 'warning',
    },
    {
      id: '37',
      chainId: 43114,
      name: 'Space Archaeologist 🪐🔍',
      balance: 78901,
      positionsCount: 37,
      marginRatioPercentage: 85,
      marginRatioHealth: 'warning',
    },
    {
      id: '38',
      chainId: 5,
      name: 'Gaming Prodigy 🎮🌟',
      balance: 23456,
      positionsCount: 38,
      marginRatioPercentage: 25,
      marginRatioHealth: 'healthy',
    },
    {
      id: '39',
      chainId: 1,
      name: 'Fitness Freak 💪🏋️‍♀️',
      balance: 54321,
      positionsCount: 39,
      marginRatioPercentage: 40,
      marginRatioHealth: 'healthy',
    },
    {
      id: '40',
      chainId: 5,
      name: 'Aviation Enthusiast ✈️🛩️',
      balance: 65432,
      positionsCount: 40,
      marginRatioPercentage: 55,
      marginRatioHealth: 'warning',
    },
    {
      id: '41',
      chainId: 1,
      name: 'Sailing Captain ⛵️⚓️',
      balance: 56789,
      positionsCount: 41,
      marginRatioPercentage: 70,
      marginRatioHealth: 'warning',
    },
    {
      id: '42',
      chainId: 43114,
      name: 'Future Technologist 🌐🔮',
      balance: 45678,
      positionsCount: 42,
      marginRatioPercentage: 85,
      marginRatioHealth: 'warning',
    },
    {
      id: '43',
      chainId: 42161,
      name: 'Art Lover 🎨🖼️',
      balance: 78901,
      positionsCount: 43,
      marginRatioPercentage: 25,
      marginRatioHealth: 'healthy',
    },
    {
      id: '44',
      chainId: 5,
      name: 'Baking Maestro 🍰👨‍🍳',
      balance: 65432,
      positionsCount: 44,
      marginRatioPercentage: 40,
      marginRatioHealth: 'healthy',
    },
    {
      id: '45',
      chainId: 43114,
      name: 'Aerial Acrobat 🤸‍♀️🪂',
      balance: 54321,
      positionsCount: 45,
      marginRatioPercentage: 55,
      marginRatioHealth: 'warning',
    },
  ];
