[GLOBAL]
pants_version = "2.15"

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy"
]

[python]
enable_resolves = true
interpreter_constraints = ["CPython==3.11.*"]

[python.resolves]
python-default = "defaultpy.lock"


