name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn lint
      - name: Check formatting
        run: yarn prettier --check 'packages/{api,indexer,utils}/src/**/*.ts'
      - name: Build packages
        run: yarn workspaces foreach -p run build
      - name: Test packages
        run: yarn workspaces foreach -p run test

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: yarn install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: npx semantic-release
