name: Release

on:
  push:
    branches:
      - main
      - feat/tidy-up-ci

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'
      - name: Configure CI Git User
        run : |
          git config --global user.name Voltz Dev
          git config --global user.email dev@voltz.xyz
      - name: Bump Updated Packages
        run: lerna version
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish packages with Lerna
        run: lerna publish from-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}