name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} Voltz Bot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install
      - name: Build packages
        run: lerna run build
      - name: Run tests
        run: lerna run test
      - name: Run coverage reports
        run: lerna run test:coverage
      - name: Configure Git, Generate coverage badges and Bump Updated Packages
        run : |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "devcold@voltz.xyz"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Voltz-Protocol/v2-off-chain-monorepo.git
          lerna run generate:coverage-badges 
          if [[ $(git status --porcelain) ]]; then
            git add .
            git commit -m "chore: update coverage badges"
          else
            echo "No changes to commit."
          fi
          lerna version
          git stash
      - name: Publish packages with Lerna
        run: lerna publish from-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}