name: Release

on:
  push:
    branches:
      - main
      - feat/tidy-up-ci
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Check NPM Whoami
        run: yarn npm whoami
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish packages with Lerna
        run: lerna publish from-package --yes
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}